mysite/mysite/urls.py
from django.conf.urls import patterns, include, url
from mysite.views import *
from mysite.contact.views import *

# Uncomment the next two lines to enable the admin:
from django.contrib import admin
admin.autodiscover()

urlpatterns = patterns('',
    ('^hello/$', hello),
    ('^$', my_homepage_view),
    ('^time/$', current_datetime),
    (r'^time/plus/(\d{1,2})/$', hours_ahead),
    (r'^first_app/$', first_app),
    (r'^current_url_view_good/$', current_url_view_good),
    (r'^display_meta/$', display_meta),
    (r'^search/$', search),
    (r'^contact/$', contact),
    (r'^contact/thanks/$', hello),
    # Examples:
    # url(r'^$', 'mysite.views.home', name='home'),
    # url(r'^mysite/', include('mysite.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    # url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:
    url(r'^admin/', include(admin.site.urls)),
)

mysite/mysite/books/models.py
from django.db import models

class Publisher(models.Model):
    name = models.CharField(max_length=30)
    address = models.CharField(max_length=50)
    city = models.CharField(max_length=60)
    state_province = models.CharField(max_length=30)
    country = models.CharField(max_length=50)
    website = models.URLField()

    def __unicode__(self):
        return self.name

class Author(models.Model):
    first_name = models.CharField(max_length=30)
    last_name = models.CharField(max_length=40)
    email = models.EmailField('e-mail', blank=True)
#    email = models.EmailField(blank=True, verbose_name='e-mail')

    def __unicode__(self):
        return u'%s %s' % (self.first_name, self.last_name)

class Book(models.Model):
    title = models.CharField(max_length=100)
    authors = models.ManyToManyField(Author)
    publisher = models.ForeignKey(Publisher)
    publication_date = models.DateField(blank=True, null=True)

    def __unicode__(self):
        return self.title

mysite/mysite/contact/forms.py
from django import forms

class ContactForm(forms.Form):
    subject = forms.CharField(max_length=100)
    email = forms.EmailField(required=False, label='Your e-mail address')
    message = forms.CharField(widget=forms.Textarea)
    
    def clean_message(self):
        message = self.cleaned_data['message']
        num_words = len(message.split())
        if num_words < 4:
            raise forms.ValidationError("Not enough words!")
        return message

mysite/mysite/books/views.py
# Create your views here.

mysite/mysite/contact/views.py
from django.core.mail import send_mail
from django.http import HttpResponseRedirect    
from django.shortcuts import render
from mysite.contact.forms import ContactForm

def contact(request):
    if request.method == 'POST':
        form = ContactForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
#            send_mail(
#                cd['subject'],
#                cd['message'],
#                cd.get('email', 'noreply@example.com'),
#                ['siteowner@example.com'],
#            )
            return HttpResponseRedirect('/contact/thanks/')
    else:
        form = ContactForm(
            initial={'subject': 'I love your site!'}
        )
    return render(request, 'contact_form.html', {'form': form})

mysite/mysite/views.py
from django.http import HttpResponse, Http404
import datetime
from django.shortcuts import render
from books.models import Publisher
from mysite.books.models import Book

def hello(request):
    return HttpResponse("Hello world")

my_homepage_view = hello

def current_datetime(request):
    now = datetime.datetime.now()
    return render(request, 'current_datetime.html', {'current_date': now})

def hours_ahead(request, offset):
    try:
        offset = int(offset)
    except ValueError:
        raise Http404()
    dt = datetime.datetime.now() + datetime.timedelta(hours=offset)
    return render(request, 'hours_ahead.html', locals())

def first_app(request):
    publisher_list = Publisher.objects.all()
    return render(request, 'first_app.html', {'publisher_list': publisher_list})

def current_url_view_good(request):
    requestList = request.__dict__.items()
    ua = request.META.get('HTTP_USER_AGENT', 'unknown')
    return render(request, 'request_list.html', locals())

def display_meta(request):
    values = request.META.items()
    values.sort()
    html = []
    for k, v in values:
        html.append('<tr><td>%s</td><td>%s</td></tr>' % (k, v))
    return HttpResponse('<table>%s</table>' % '\n'.join(html))

def search(request):
    errors = []
    if 'q' in request.GET:
        q = request.GET['q']
        if not q:
            errors.append('Enter a search term.')
        elif len(q) > 20:
            errors.append('Please enter at most 20 characters.')
        else:
            books = Book.objects.filter(title__icontains=q)
            return render(request, 'search_results.html',
                {'books': books, 'query': q})
    return render(request, 'search_form.html',
        {'errors': errors})

mysite/mysite/templates/base.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <title>{% block title %}{% endblock %}</title>
</head>
<body>
    <h1>My helpful timestamp site</h1>
    {% block content %}{% endblock %}
    {% block footer %}
    <hr>
    <p>Thanks for visiting my site.</p>
    {% endblock %}
</body>
</html>

mysite/mysite/templates/contact_form.html
<style type="text/css">
    ul.errorlist {
        margin: 0;
        padding: 0;
    }
    .errorlist li {
        background-color: red;
        color: white;
        display: block;
        font-size: 10px;
        margin: 0 0 3px;
        padding: 4px 5px;
    }
</style>

<html>
<head>
    <title>Contact us</title>
</head>
<body>
    <h1>Contact us</h1>

    {% if form.errors %}
        <p style="color: red;">
            Please correct the error{{ form.errors|pluralize }} below.
        </p>
    {% endif %}

    <form action="" method="post">
        <div class="field">
            {{ form.subject.errors }}
            <label for="id_subject">Subject:</label>
            {{ form.subject }}
        </div>
        <div class="field">
            {{ form.email.errors }}
            <label for="id_email">Your e-mail address:</label>
            {{ form.email }}
        </div>
		<div class="field{% if form.message.errors %} errors{% endif %}">
		    {% if form.message.errors %}
		        <ul>
		        {% for error in form.message.errors %}
		            <li><strong>{{ error }}</strong></li>
		        {% endfor %}
		        </ul>
		    {% endif %}
		    <label for="id_message">Message:</label>
		    {{ form.message }}
		</div>
        <input type="submit" value="Submit">
    </form>
</body>
</html>

mysite/mysite/templates/current_datetime.html
{% extends "base.html" %}

{% block title %}The current time{% endblock %}

{% block content %}
<p>It is now {{ current_date }}.</p>
{% endblock %}

mysite/mysite/templates/first_app.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <title>First App</title>
</head>
<body>
	<h3>The Publish Name List:</h3>
    {% for publisher in publisher_list %}
    	{{ forloop.counter }}. {{ publisher }}
    	<br/>
    {% endfor %}
</body>
</html>

mysite/mysite/templates/hours_ahead.html
{% extends "base.html" %}

{% block title %}Future time{% endblock %}

{% block content %}
<p>In {{ offset }} hour(s), it will be {{ dt }}.</p>
{% endblock %}

mysite/mysite/templates/request_list.html
<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN">
<html lang="en">
<head>
    <title>Http Request</title>
</head>
<body>
	<h3>Http Request Function:</h3>
	request.get_host() => {{ request.get_host }} 
	<br/><br/>
	request.get_full_path() => {{ request.get_full_path }} 
	<br/><br/>
	request.is_secure() => {{ request.is_secure }} 
	<br/><br/>
	UA => {{ ua }}
	
	<h3>Http Request Variable:</h3>
    {% for item in requestList %}
    	{{ forloop.counter }} : {{ item.0 }} => {{ item.1 }}
    	<br/><br/>
    {% endfor %}
</body>
</html>

mysite/mysite/templates/search_form.html
<html>
<head>
    <title>Search</title>
</head>
<body>
    {% if errors %}
        <ul>
            {% for error in errors %}
            <li>{{ error }}</li>
            {% endfor %}
        </ul>
    {% endif %}
    <form action="/search/" method="get">
        <input type="text" name="q">
        <input type="submit" value="Search">
    </form>
</body>
</html>

mysite/mysite/templates/search_results.html
<p>You searched for: <strong>{{ query }}</strong></p>

{% if books %}
    <p>Found {{ books|length }} book{{ books|pluralize }}.</p>
    <ul>
        {% for book in books %}
        <li>{{ book.title }}</li>
        {% endfor %}
    </ul>
{% else %}
    <p>No books matched your search criteria.</p>
{% endif %}